export enum ErrorMessage {
  NAME_REQUIRED = 'NAME_REQUIRED',
  BAD_REQUEST = 'BAD_REQUEST',
  CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND',
  NAME_ALREADY_TAKEN = 'NAME_ALREADY_TAKEN',
  SELF_MESSAGE = 'SELF_MESSAGE',
}
